MAX_DEFAULT_SIGNAL_RANGE = 10

CCTV_CAMERA = {}
CCTV_CAMERA_NV = {}
CCTV_CAMERA_PURE = {}
CCTV_CAMERA_PREMIUM = {}

local CAMERA_FILTERS = {
    GRAY_SCALE = 1,
    RGB = 2,
}

local QUALITY_FILTER = {
    GLITCH = 1,
    LINES = 2,
    LOW_GROUND_NOISE = 3,
    NONE = 4
}


-- Дефолтная камера
CCTV_CAMERA.SIGNAL_RANGE = MAX_DEFAULT_SIGNAL_RANGE
CCTV_CAMERA.NIGHT_VISION = false
CCTV_CAMERA.QUALITY_FILTER = QUALITY_FILTER.LOW_GROUND_NOISE
CCTV_CAMERA_NV.LENS_FILTER = QUALITY_FILTER.RGB


-- Дефолтная камера с ночным режимом
CCTV_CAMERA_NV.SIGNAL_RANGE = MAX_DEFAULT_SIGNAL_RANGE
CCTV_CAMERA_NV.NIGHT_VISION = true
CCTV_CAMERA_NV.QUALITY_FILTER = QUALITY_FILTER.LOW_GROUND_NOISE
CCTV_CAMERA_NV.LENS_FILTER = QUALITY_FILTER.GRAY_SCALE

-- Premium
CCTV_CAMERA_PREMIUM.SIGNAL_RANGE = MAX_DEFAULT_SIGNAL_RANGE + 20
CCTV_CAMERA_PREMIUM.NIGHT_VISION = true
CCTV_CAMERA_PREMIUM.LENS_FILTER = CAMERA_FILTERS.RGB
CCTV_CAMERA_PREMIUM.QUALITY_FILTER = QUALITY_FILTER.NONE

-- Кустарная или дешевая камера (скорее всего оставлю ее как кустарную)
CCTV_CAMERA_PURE.SIGNAL_RANGE = MAX_DEFAULT_SIGNAL_RANGE
CCTV_CAMERA_PURE.NIGHT_VISION = false
CCTV_CAMERA_PURE.LENS_FILTER = CAMERA_FILTERS.GRAY_SCALE
CCTV_CAMERA_PURE.QUALITY_FILTER = QUALITY_FILTER.GLITCH